<?php

namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * this function get all books available for delvery
    */
    public function getAvailableBooks(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT b FROM AppBundle:Book b LEFT JOIN b.deliveries d WHERE d.isReturned = TRUE OR d.id IS NULL'
            )
          ->getResult();
    }
}
