<?php

namespace AppBundle\Repository;

/**
 * deliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class deliveryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * this function get the user's deliveries pending to return
    */
    public function getUserDeliveries($user_id){
      return $this->getEntityManager()
          ->createQuery(
              'SELECT d,b FROM AppBundle:delivery d JOIN d.user u JOIN d.book b WHERE u.id = :id'
          )
        ->setParameter('id',$user_id)
        ->getResult();
    }
}
