<?php

namespace AppBundle\Repository;

/**
 * ReturnsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReturnsRepository extends \Doctrine\ORM\EntityRepository
{
}
